weights: weights/yolov5s.pt
cfg: configs/segment/yolov5s_seg.yaml
data: ./data/seg/coco_person.yaml
hyp: data/hyps/hyp.scratch.yaml
epochs: 50
batch_size: 8
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
bucket: ''
cache: null
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
workers: 8
project: runs/test
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
patience: 100
freeze: 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
neg_dir: ''
bg_dir: ''
area_thr: 0.2
no_aug_epochs: 15
mask: true
mask_ratio: 4
